### PR TITLE
[Stable] add piping and some stability to the ls command

### LINKED ISSUE #51: Add pipes
add stdin/stdout piping like bash has

### PR DESCRIPTION
**Pull request by JesterOrNot**
fixes #51

### CODE REVIEW

**Comment by JesterOrNot** [comment]
@RDIL any feedback?

**Comment by RDIL** [comment]
Approval means looks good and no other feedback

**Comment by JesterOrNot** [comment]
@RDIL sorry my bad!

**Comment by RDIL** [comment]
Its fine

**Comment by JesterOrNot** [comment]
fixes #51

**Comment by JesterOrNot** [comment]
@RDIL What are you proposing?

**Comment by RDIL** [comment]
Spaces instead of tabs

**Comment by JesterOrNot** [comment]
@RDIL any better?

**Comment by JesterOrNot** [comment]
@RDIL I'm merging it open a separate issue later if you have any issues with the spacing or send a PR with the preferred spacing

**Pull request merged**
