### PR TITLE
Run tests

### PR DESCRIPTION
**Pull request by RDIL**
alpha stage dnm

### CODE REVIEW

**Comment by RDIL** [comment]
@JesterOrNot we have our first green light

p.s. you know python right because if so please help write tests

**Comment by JesterOrNot** [comment]
What tests need to be written

**Comment by RDIL** [comment]
All of them - covering most use cases for essentially every command

**Comment by JesterOrNot** [comment]
Why close this?

**Comment by RDIL** [comment]
I don't have enough time to finish it.

**Pull request closed without merging**
